---
bibliography: ["all_my_refs.bib"]
csl: "styles/nature-communications.csl"
title: "Lorem Ipsum"
link citations: true
figPrefix:
    - "Fig."
    - "Figs."
linkReferences: true
nameInLink: true
papersize: a4
colorlinks: true
links-as-notes: true
figureTitle: "**Figure**"
captionDelim: "."
indent: true

header-includes: |
 \usepackage{setspace}
 \doublespacing
 \usepackage{hanging}
 \usepackage{caption}
 \captionsetup{labelsep=period}

 \usepackage{authblk}
 \author[1, 2]{Leonard Sasse \thanks{l.sasse@fz-juelich.de}}

 \affil[1]{Institute of Neuroscience and Medicine, Brain and Behaviour (INM-7), Research Centre J端lich, J端lich, Germany}
 \affil[2]{Institute of Systems Neuroscience, Medical Faculty, Heinrich-Heine-University D端sseldorf, D端sseldorf, Germany}

date: \today
abstract: |
    Consequat ex consectetur qui officia enim Lorem labore dolor proident 
    incididunt ullamco aute. Est consectetur sit non laborum adipisicing est. 
    Commodo minim dolor deserunt voluptate.Mollit non sunt nisi incididunt tempor
    est esse aute. Ullamco velit tempor est culpa commodo deserunt esse anim 
    officia reprehenderit occaecat sit amet mollit. Eiusmod amet voluptate esse
    sunt consequat anim eiusmod fugiat ea magna commodo consectetur sunt.
    Non nisi nulla sint ut exercitation nulla ad.
---
